"""add cancellation_reason to return_requests table

Revision ID: 044a4b65e17f
Revises: a2de4da10b74
Create Date: 2025-11-21 18:37:23.452179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044a4b65e17f'
down_revision: Union[str, Sequence[str], None] = 'a2de4da10b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_requests', sa.Column('cancellation_reason', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_requests', 'cancellation_reason')
    # ### end Alembic commands ###
