"""request_date can be null - for cancel return

Revision ID: 09c595f557a8
Revises: 044a4b65e17f
Create Date: 2025-11-21 18:41:44.311972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c595f557a8'
down_revision: Union[str, Sequence[str], None] = '044a4b65e17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('return_requests', 'request_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='Request date from API in YYYY-MM-DD format')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('return_requests', 'request_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_comment='Request date from API in YYYY-MM-DD format')
    # ### end Alembic commands ###
