"""Validate database schema

Revision ID: 09ff43d6efb8
Revises: 4f54aa23083b
Create Date: 2025-11-19 07:25:21.537502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '09ff43d6efb8'
down_revision: Union[str, Sequence[str], None] = '4f54aa23083b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_code_type'), table_name='nc_response_codes')
    op.drop_index(op.f('response_code'), table_name='nc_response_codes')
    op.drop_table('nc_response_codes')
    op.drop_index(op.f('idx_completion'), table_name='cancellation_requests')
    op.drop_index(op.f('idx_created_country'), table_name='cancellation_requests')
    op.drop_index(op.f('idx_main_query'), table_name='cancellation_requests')
    op.drop_index(op.f('idx_scheduled_status'), table_name='cancellation_requests')
    op.drop_index(op.f('idx_unique_reference'), table_name='cancellation_requests')
    op.drop_table('cancellation_requests')
    op.drop_index(op.f('idx_action'), table_name='portability_audit_log')
    op.drop_index(op.f('idx_created_at'), table_name='portability_audit_log')
    op.drop_index(op.f('idx_request_id'), table_name='portability_audit_log')
    op.drop_table('portability_audit_log')
    op.drop_index(op.f('idx_created_at'), table_name='portability_requests_v0')
    op.drop_index(op.f('idx_msisdn'), table_name='portability_requests_v0')
    op.drop_index(op.f('idx_phone_number'), table_name='portability_requests_v0')
    op.drop_index(op.f('idx_session_code'), table_name='portability_requests_v0')
    op.drop_index(op.f('idx_status'), table_name='portability_requests_v0')
    op.drop_table('portability_requests_v0')
    op.alter_column('portability_requests', 'nationality',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("'ESP'"))
    op.drop_index(op.f('idx_completion'), table_name='portability_requests')
    op.drop_index(op.f('idx_country_type'), table_name='portability_requests')
    op.drop_index(op.f('idx_created_at'), table_name='portability_requests')
    op.drop_index(op.f('idx_document'), table_name='portability_requests')
    op.drop_index(op.f('idx_donor_recipient'), table_name='portability_requests')
    op.drop_index(op.f('idx_msisdn'), table_name='portability_requests')
    op.drop_index(op.f('idx_reference_code'), table_name='portability_requests')
    op.drop_index(op.f('idx_scheduled_status'), table_name='portability_requests')
    op.drop_index(op.f('idx_session_code'), table_name='portability_requests')
    op.drop_index(op.f('idx_status_composite'), table_name='portability_requests')
    op.drop_table_comment(
        'portability_requests',
        existing_comment='Mobile number portability requests (IN/OUT/CANCEL/MULTISIM)',
        schema=None
    )
    op.drop_index(op.f('idx_response_code'), table_name='portout_metadata')
    op.alter_column('portout_request', 'submitted_to_bss',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='0 - not subitted ,1 - submitted',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('portout_request', 'confirm_reject',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_comment='confirm=1, reject=2 for offline confirmation to NC',
               existing_nullable=True)
    op.alter_column('portout_request', 'description',
               existing_type=mysql.VARCHAR(length=200),
               comment='description with return NC on reject or confirm',
               existing_comment='descroption with return NC on reject or confirm',
               existing_nullable=True)
    op.alter_column('portout_request', 'subscriber_type',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='person or legal',
               existing_nullable=True,
               existing_server_default=sa.text("'person'"))
    op.drop_index(op.f('idx_metadata_id'), table_name='portout_request')
    op.drop_index(op.f('idx_msisdn'), table_name='portout_request')
    op.drop_index(op.f('idx_reference_code'), table_name='portout_request')
    op.drop_constraint(op.f('portout_request_ibfk_1'), 'portout_request', type_='foreignkey')
    op.create_foreign_key(None, 'portout_request', 'portout_metadata', ['metadata_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portout_request', type_='foreignkey')
    op.create_foreign_key(op.f('portout_request_ibfk_1'), 'portout_request', 'portout_metadata', ['metadata_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_reference_code'), 'portout_request', ['reference_code'], unique=False)
    op.create_index(op.f('idx_msisdn'), 'portout_request', ['MSISDN'], unique=False)
    op.create_index(op.f('idx_metadata_id'), 'portout_request', ['metadata_id'], unique=False)
    op.alter_column('portout_request', 'subscriber_type',
               existing_type=mysql.VARCHAR(length=20),
               comment='person or legal',
               existing_nullable=True,
               existing_server_default=sa.text("'person'"))
    op.alter_column('portout_request', 'description',
               existing_type=mysql.VARCHAR(length=200),
               comment='descroption with return NC on reject or confirm',
               existing_comment='description with return NC on reject or confirm',
               existing_nullable=True)
    op.alter_column('portout_request', 'confirm_reject',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_comment='confirm=1, reject=2 for offline confirmation to NC',
               existing_nullable=True)
    op.alter_column('portout_request', 'submitted_to_bss',
               existing_type=mysql.TINYINT(display_width=1),
               comment='0 - not subitted ,1 - submitted',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_response_code'), 'portout_metadata', ['response_code'], unique=False)
    op.create_table_comment(
        'portability_requests',
        'Mobile number portability requests (IN/OUT/CANCEL/MULTISIM)',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_status_composite'), 'portability_requests', ['status_nc', 'status_bss', 'scheduled_at'], unique=False)
    op.create_index(op.f('idx_session_code'), 'portability_requests', ['session_code'], unique=False)
    op.create_index(op.f('idx_scheduled_status'), 'portability_requests', ['scheduled_at', 'status_nc'], unique=False)
    op.create_index(op.f('idx_reference_code'), 'portability_requests', ['reference_code'], unique=False)
    op.create_index(op.f('idx_msisdn'), 'portability_requests', ['msisdn'], unique=False)
    op.create_index(op.f('idx_donor_recipient'), 'portability_requests', ['donor_operator', 'recipient_operator'], unique=False)
    op.create_index(op.f('idx_document'), 'portability_requests', ['document_type', 'document_number'], unique=False)
    op.create_index(op.f('idx_created_at'), 'portability_requests', ['created_at'], unique=False)
    op.create_index(op.f('idx_country_type'), 'portability_requests', ['country_code', 'request_type'], unique=False)
    op.create_index(op.f('idx_completion'), 'portability_requests', ['completed_at', 'country_code'], unique=False)
    op.alter_column('portability_requests', 'nationality',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=True,
               existing_server_default=sa.text("'ESP'"))
    op.create_table('portability_requests_v0',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('session_code', mysql.VARCHAR(length=255), nullable=True, comment='codigoSesion'),
    sa.Column('request_type', mysql.VARCHAR(length=255), nullable=True, comment='eg port_in or port_out'),
    sa.Column('country_code', mysql.VARCHAR(length=3), server_default=sa.text("'ESP'"), nullable=True),
    sa.Column('status_bss', mysql.VARCHAR(length=255), nullable=True, comment='status of bss query'),
    sa.Column('status_nc', mysql.VARCHAR(length=255), nullable=True, comment='status of nc query'),
    sa.Column('retry_number', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='number of retries'),
    sa.Column('error_description', mysql.VARCHAR(length=255), server_default=sa.text("''"), nullable=True, comment='resaon of retry'),
    sa.Column('request_date', sa.DATE(), nullable=True, comment='fechaSolicitudPorAbonado'),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True, comment='eg Solicitud creada exitosamente'),
    sa.Column('donor_operator', mysql.VARCHAR(length=50), nullable=True, comment='codigoOperadorDonante'),
    sa.Column('recipient_operator', mysql.VARCHAR(length=50), nullable=True, comment='codigoOperadorReceptor'),
    sa.Column('id_type', mysql.VARCHAR(length=20), nullable=True, comment='abonado.documentoIdentificacion.tipo'),
    sa.Column('id_number', mysql.VARCHAR(length=50), nullable=True, comment='abonado.documentoIdentificacion.documento'),
    sa.Column('contract_code', mysql.VARCHAR(length=100), nullable=True, comment='codigoContrato'),
    sa.Column('nrn_receptor', mysql.VARCHAR(length=100), nullable=True, comment='NRNReceptor'),
    sa.Column('porting_window_date', sa.DATE(), nullable=True, comment='fechaVentanaCambio'),
    sa.Column('iccid', mysql.VARCHAR(length=20), nullable=True, comment='ICCID'),
    sa.Column('msisdn', mysql.VARCHAR(length=15), nullable=True, comment='MSISDN'),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True, comment='Alternative to MSISDN'),
    sa.Column('status', mysql.ENUM('PENDING_SUBMIT', 'ASOL', 'ACON', 'AREC', 'APOR'), server_default=sa.text("'PENDING_SUBMIT'"), nullable=True),
    sa.Column('response_status', mysql.VARCHAR(length=255), nullable=True, comment='resopnce status, eg 200'),
    sa.Column('requested_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('scheduled_at', mysql.DATETIME(), nullable=True, comment='time if future for the next query to NC'),
    sa.Column('actual_porting_time', mysql.DATETIME(), nullable=True),
    sa.Column('rejection_reason', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_spanish_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.Column('next_check_at', mysql.DATETIME(), nullable=True),
    sa.Column('check_status', mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED'), server_default=sa.text("'PENDING'"), nullable=True),
    sa.Column('retry_count', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_checked_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_status'), 'portability_requests_v0', ['status'], unique=False)
    op.create_index(op.f('idx_session_code'), 'portability_requests_v0', ['session_code'], unique=False)
    op.create_index(op.f('idx_phone_number'), 'portability_requests_v0', ['phone_number'], unique=False)
    op.create_index(op.f('idx_msisdn'), 'portability_requests_v0', ['msisdn'], unique=False)
    op.create_index(op.f('idx_created_at'), 'portability_requests_v0', ['created_at'], unique=False)
    op.create_table('portability_audit_log',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('request_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('action', mysql.VARCHAR(length=50), nullable=False, comment='STATUS_CHANGE/RESPONSE_RECEIVED/RETRY_ATTEMPT'),
    sa.Column('old_status_nc', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('new_status_nc', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('old_status_bss', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('new_status_bss', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('response_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('details', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True, comment='Full request/response payload'),
    sa.Column('performed_by', mysql.VARCHAR(length=100), server_default=sa.text("'system'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['portability_requests.id'], name=op.f('portability_audit_log_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Audit trail for all portability request changes',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Audit trail for all portability request changes',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_request_id'), 'portability_audit_log', ['request_id'], unique=False)
    op.create_index(op.f('idx_created_at'), 'portability_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('idx_action'), 'portability_audit_log', ['action'], unique=False)
    op.create_table('cancellation_requests',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('reference_code', mysql.VARCHAR(length=100), nullable=False, comment='Original portability reference'),
    sa.Column('cancellation_reason', mysql.VARCHAR(length=100), nullable=False, comment='Reason for cancellation'),
    sa.Column('cancellation_initiated_by_donor', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='Whether donor operator initiated'),
    sa.Column('status_nc', mysql.VARCHAR(length=50), server_default=sa.text("'PENDING'"), nullable=True, comment='NC system status'),
    sa.Column('status_bss', mysql.VARCHAR(length=50), server_default=sa.text("'PROCESSING'"), nullable=True, comment='BSS system status'),
    sa.Column('session_code', mysql.VARCHAR(length=100), nullable=True, comment='NC session identifier'),
    sa.Column('request_type', mysql.VARCHAR(length=20), server_default=sa.text("'cancellation'"), nullable=True, comment='Request type'),
    sa.Column('country_code', mysql.VARCHAR(length=3), server_default=sa.text("'ESP'"), nullable=True, comment='Country code'),
    sa.Column('scheduled_at', mysql.TIMESTAMP(), nullable=True, comment='When to process this request'),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True, comment='Record creation time'),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True, comment='Last update time'),
    sa.Column('completed_at', mysql.TIMESTAMP(), nullable=True, comment='When cancellation was completed'),
    sa.Column('attempt_count', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='Number of processing attempts'),
    sa.Column('last_error', mysql.TEXT(), nullable=True, comment='Last error message'),
    sa.Column('original_request_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='Reference to original portability request'),
    sa.Column('metadata', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True, comment='Additional flexible data'),
    sa.PrimaryKeyConstraint('id'),
    comment='Portability cancellation requests',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='Portability cancellation requests',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_unique_reference'), 'cancellation_requests', ['reference_code'], unique=True)
    op.create_index(op.f('idx_scheduled_status'), 'cancellation_requests', ['scheduled_at', 'status_nc'], unique=False)
    op.create_index(op.f('idx_main_query'), 'cancellation_requests', ['status_nc', 'status_bss', 'scheduled_at', 'country_code'], unique=False)
    op.create_index(op.f('idx_created_country'), 'cancellation_requests', ['created_at', 'country_code'], unique=False)
    op.create_index(op.f('idx_completion'), 'cancellation_requests', ['completed_at', 'country_code'], unique=False)
    op.create_table('nc_response_codes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('response_code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('request_type', mysql.ENUM('PORT_IN', 'PORT_OUT', 'CANCELLATION', 'MULTISIM'), nullable=False),
    sa.Column('meaning', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('is_success', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('should_retry', mysql.TINYINT(display_width=1), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='NC response codes mapping',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='NC response codes mapping',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('response_code'), 'nc_response_codes', ['response_code'], unique=True)
    op.create_index(op.f('idx_code_type'), 'nc_response_codes', ['response_code', 'request_type'], unique=False)
    # ### end Alembic commands ###
