"""ITA 3 tables creation

Revision ID: 0b1e32600ebd
Revises: 16de489f395e
Create Date: 2025-12-07 17:46:14.857305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1e32600ebd'
down_revision: Union[str, Sequence[str], None] = '16de489f395e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('italy_port_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_request_code', sa.String(length=50), nullable=True),
    sa.Column('msisdn', sa.String(length=20), nullable=True),
    sa.Column('message_type_code', sa.String(length=2), nullable=True),
    sa.Column('process_status', sa.String(length=50), nullable=True),
    sa.Column('cut_over_date', sa.Date(), nullable=True),
    sa.Column('xml', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Main table for Italy MNP porting requests',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_request_cutover_status', 'italy_port_requests', ['cut_over_date', 'process_status'], unique=False)
    op.create_index('idx_request_msisdn_status', 'italy_port_requests', ['msisdn', 'process_status'], unique=False)
    op.create_index('idx_request_type_status', 'italy_port_requests', ['message_type_code', 'process_status'], unique=False)
    op.create_index(op.f('ix_italy_port_requests_created_at'), 'italy_port_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_italy_port_requests_cut_over_date'), 'italy_port_requests', ['cut_over_date'], unique=False)
    op.create_index(op.f('ix_italy_port_requests_message_type_code'), 'italy_port_requests', ['message_type_code'], unique=False)
    op.create_index(op.f('ix_italy_port_requests_msisdn'), 'italy_port_requests', ['msisdn'], unique=False)
    op.create_index(op.f('ix_italy_port_requests_process_status'), 'italy_port_requests', ['process_status'], unique=False)
    op.create_index(op.f('ix_italy_port_requests_recipient_request_code'), 'italy_port_requests', ['recipient_request_code'], unique=True)
    op.create_table('italy_port_in_scheduled_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portin_request_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False, comment='SEND_MSG2, CHECK_STATUS, RETRY, NOTIFY_BSS, CLEANUP'),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False, comment='When to execute (UTC)'),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False, comment='PENDING, EXECUTING, COMPLETED, FAILED, CANCELLED'),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('depends_on_message_type', sa.String(length=2), nullable=True, comment='Wait for this message type (1-13) before executing'),
    sa.Column('depends_on_status', sa.String(length=50), nullable=True, comment='Wait for this status before executing'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Hard stop - never execute after this (UTC)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['portin_request_id'], ['italy_port_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Future actions scheduled for porting requests',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_scheduled_dependencies', 'italy_port_in_scheduled_actions', ['depends_on_message_type', 'depends_on_status'], unique=False)
    op.create_index('idx_scheduled_due', 'italy_port_in_scheduled_actions', ['status', 'scheduled_at'], unique=False)
    op.create_index('idx_scheduled_expired', 'italy_port_in_scheduled_actions', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_italy_port_in_scheduled_actions_executed_at'), 'italy_port_in_scheduled_actions', ['executed_at'], unique=False)
    op.create_index(op.f('ix_italy_port_in_scheduled_actions_portin_request_id'), 'italy_port_in_scheduled_actions', ['portin_request_id'], unique=False)
    op.create_index(op.f('ix_italy_port_in_scheduled_actions_scheduled_at'), 'italy_port_in_scheduled_actions', ['scheduled_at'], unique=False)
    op.create_table('italy_port_in_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portin_request_id', sa.Integer(), nullable=False),
    sa.Column('message_type_code', sa.String(length=2), nullable=False, comment='Message type code (1-13) when status changed'),
    sa.Column('status_reason', sa.String(length=100), nullable=True, comment='Why status changed: timeout, manual, system, etc.'),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True, comment='Additional context: error details, response XML, etc.'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['portin_request_id'], ['italy_port_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Audit trail of all status changes for porting requests',
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_status_history_new_status', 'italy_port_in_status_history', ['new_status', 'created_at'], unique=False)
    op.create_index('idx_status_history_request_status', 'italy_port_in_status_history', ['portin_request_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_italy_port_in_status_history_created_at'), 'italy_port_in_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_italy_port_in_status_history_portin_request_id'), 'italy_port_in_status_history', ['portin_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_italy_port_in_status_history_portin_request_id'), table_name='italy_port_in_status_history')
    op.drop_index(op.f('ix_italy_port_in_status_history_created_at'), table_name='italy_port_in_status_history')
    op.drop_index('idx_status_history_request_status', table_name='italy_port_in_status_history')
    op.drop_index('idx_status_history_new_status', table_name='italy_port_in_status_history')
    op.drop_table('italy_port_in_status_history')
    op.drop_index(op.f('ix_italy_port_in_scheduled_actions_scheduled_at'), table_name='italy_port_in_scheduled_actions')
    op.drop_index(op.f('ix_italy_port_in_scheduled_actions_portin_request_id'), table_name='italy_port_in_scheduled_actions')
    op.drop_index(op.f('ix_italy_port_in_scheduled_actions_executed_at'), table_name='italy_port_in_scheduled_actions')
    op.drop_index('idx_scheduled_expired', table_name='italy_port_in_scheduled_actions')
    op.drop_index('idx_scheduled_due', table_name='italy_port_in_scheduled_actions')
    op.drop_index('idx_scheduled_dependencies', table_name='italy_port_in_scheduled_actions')
    op.drop_table('italy_port_in_scheduled_actions')
    op.drop_index(op.f('ix_italy_port_requests_recipient_request_code'), table_name='italy_port_requests')
    op.drop_index(op.f('ix_italy_port_requests_process_status'), table_name='italy_port_requests')
    op.drop_index(op.f('ix_italy_port_requests_msisdn'), table_name='italy_port_requests')
    op.drop_index(op.f('ix_italy_port_requests_message_type_code'), table_name='italy_port_requests')
    op.drop_index(op.f('ix_italy_port_requests_cut_over_date'), table_name='italy_port_requests')
    op.drop_index(op.f('ix_italy_port_requests_created_at'), table_name='italy_port_requests')
    op.drop_index('idx_request_type_status', table_name='italy_port_requests')
    op.drop_index('idx_request_msisdn_status', table_name='italy_port_requests')
    op.drop_index('idx_request_cutover_status', table_name='italy_port_requests')
    op.drop_table('italy_port_requests')
    # ### end Alembic commands ###
