"""Initial schema

Revision ID: 16de489f395e
Revises: 
Create Date: 2025-12-05 16:09:28.497854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16de489f395e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('italy_port_in_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_operator', sa.String(length=50), nullable=False),
    sa.Column('file_date', sa.Date(), nullable=False),
    sa.Column('file_time', sa.String(length=8), nullable=False),
    sa.Column('recipient_operator', sa.String(length=50), nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=False),
    sa.Column('message_type_code', sa.String(length=2), nullable=False),
    sa.Column('recipient_operator_code', sa.String(length=50), nullable=False),
    sa.Column('donating_operator_code', sa.String(length=50), nullable=False),
    sa.Column('recipient_request_code', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('iccid_serial_number', sa.String(length=20), nullable=True),
    sa.Column('tax_code_vat', sa.String(length=50), nullable=True),
    sa.Column('payment_type', sa.String(length=3), nullable=True),
    sa.Column('analog_digital_code', sa.String(length=1), nullable=True),
    sa.Column('cut_over_date', sa.Date(), nullable=False),
    sa.Column('customer_first_name', sa.String(length=100), nullable=True),
    sa.Column('customer_last_name', sa.String(length=100), nullable=True),
    sa.Column('imsi', sa.String(length=20), nullable=True),
    sa.Column('credit_transfer_flag', sa.String(length=1), nullable=True),
    sa.Column('routing_number', sa.String(length=10), nullable=True),
    sa.Column('pre_validation_flag', sa.String(length=1), nullable=True),
    sa.Column('theft_flag', sa.String(length=1), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='When this request is scheduled for processing'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient_request_code')
    )
    op.create_table('portability_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=3), server_default=sa.text("'ESP'"), nullable=False),
    sa.Column('request_type', sa.Enum('PORT_IN', 'PORT_OUT', 'CANCELLATION', 'MULTISIM', 'EXTENSION', name='request_type_enum'), nullable=False),
    sa.Column('cancel_request_id', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='id of portin request'),
    sa.Column('reference_code', sa.String(length=100), server_default=sa.text("''"), nullable=True, comment='Unique reference from NC system'),
    sa.Column('session_code', sa.String(length=100), nullable=True, comment='Session identifier from BSS'),
    sa.Column('session_code_nc', sa.String(length=100), nullable=True, comment='Session identifier from NC'),
    sa.Column('request_code', sa.String(length=100), nullable=True, comment='Internal request identifier'),
    sa.Column('status_bss', sa.String(length=100), server_default=sa.text("'PROCESSING'"), nullable=True, comment='BSS system status'),
    sa.Column('status_nc', sa.String(length=50), server_default=sa.text("'PENDING'"), nullable=True, comment='NC system status'),
    sa.Column('response_code', sa.String(length=20), server_default=sa.text("''"), nullable=True, comment='coddigoRespuesta'),
    sa.Column('response_status', sa.String(length=20), server_default=sa.text("''"), nullable=True, comment='Latest response code from NC'),
    sa.Column('reject_code', sa.String(length=10), server_default=sa.text("''"), nullable=True, comment='reject status eg RECH_BNUME RECH_PERDI RECH_IDENT RECH_ICCID'),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message'),
    sa.Column('error_description', sa.String(length=255), nullable=True),
    sa.Column('msisdn', sa.String(length=15), server_default=sa.text("''"), nullable=False, comment='Phone number'),
    sa.Column('iccid', sa.String(length=22), nullable=True, comment='SIM card number'),
    sa.Column('subscriber_type', sa.Enum('person', 'company', name='subscriber_type_enum'), nullable=True, comment='person/company'),
    sa.Column('document_type', sa.Enum('NIF', 'CIF', 'NIE', 'PAS', name='document_type_enum'), nullable=False),
    sa.Column('document_number', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('first_surname', sa.String(length=100), nullable=True),
    sa.Column('second_surname', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=64), server_default=sa.text("'España'"), nullable=True),
    sa.Column('name_surname', sa.String(length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True, comment='Subscriber contract number'),
    sa.Column('donor_operator', sa.String(length=50), server_default=sa.text("''"), nullable=False, comment='Current operator'),
    sa.Column('recipient_operator', sa.String(length=50), server_default=sa.text("''"), nullable=False, comment='New operator'),
    sa.Column('routing_number', sa.String(length=20), server_default=sa.text("''"), nullable=True, comment='Routing information'),
    sa.Column('desired_porting_date', sa.String(length=20), nullable=True),
    sa.Column('porting_window', sa.DateTime(), nullable=True, comment='Scheduled porting window date/time from NC'),
    sa.Column('reason_code', sa.String(length=50), nullable=True, comment='Reason for port-out'),
    sa.Column('cancellation_reason', sa.String(length=150), nullable=True),
    sa.Column('cancellation_initiated_by_donor', sa.String(length=150), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(), nullable=True, comment='When customer requested'),
    sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=True, comment='When to process next'),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True, comment='When request completed'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_legal_entity', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='Flag indicating if this is a legal entity (1) or individual (0)'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Company name for legal entities'),
    sa.PrimaryKeyConstraint('id'),
    comment='Mobile number portability requests (IN/OUT/CANCEL/MULTISIM)'
    )
    op.create_index('idx_completion', 'portability_requests', ['completed_at', 'country_code'], unique=False)
    op.create_index('idx_country_type', 'portability_requests', ['country_code', 'request_type'], unique=False)
    op.create_index('idx_created_at', 'portability_requests', ['created_at'], unique=False)
    op.create_index('idx_document', 'portability_requests', ['document_type', 'document_number'], unique=False)
    op.create_index('idx_donor_recipient', 'portability_requests', ['donor_operator', 'recipient_operator'], unique=False)
    op.create_index('idx_msisdn', 'portability_requests', ['msisdn'], unique=False)
    op.create_index('idx_reference_code', 'portability_requests', ['reference_code'], unique=False)
    op.create_index('idx_scheduled_status', 'portability_requests', ['scheduled_at', 'status_nc'], unique=False)
    op.create_index('idx_session_code', 'portability_requests', ['session_code'], unique=False)
    op.create_index('idx_status_composite', 'portability_requests', ['status_nc', 'status_bss', 'scheduled_at'], unique=False)
    op.create_table('portout_metadata',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('response_code', sa.String(length=50), nullable=True),
    sa.Column('response_description', sa.String(length=255), nullable=True),
    sa.Column('paged_request_code', sa.String(length=100), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('is_last_page', sa.Boolean(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_response_code', 'portout_metadata', ['response_code'], unique=False)
    op.create_table('return_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_type', sa.String(length=20), server_default=sa.text("'RETURN'"), nullable=False, comment='Request type: RETURN'),
    sa.Column('request_date', sa.Date(), nullable=True, comment='Request date from API in YYYY-MM-DD format'),
    sa.Column('msisdn', sa.String(length=15), nullable=True, comment='Phone number (9 digits without country code)'),
    sa.Column('cancellation_reason', sa.String(length=150), nullable=True),
    sa.Column('reference_code', sa.String(length=100), nullable=True, comment='CodigoReferencia - Unique reference from NC system'),
    sa.Column('status_bss', sa.String(length=50), server_default=sa.text("'PROCESSING'"), nullable=True, comment='BSS system status: PROCESSING, COMPLETED, FAILED'),
    sa.Column('status_nc', sa.String(length=50), server_default=sa.text("'PENDING'"), nullable=True, comment='NC system status: PENDING, PENDING_RESPONSE, COMPLETED, FAILED'),
    sa.Column('response_code', sa.String(length=20), nullable=True, comment='codigoRespuesta from NC response'),
    sa.Column('response_status', sa.String(length=20), nullable=True, comment='estado - latest response status from NC'),
    sa.Column('reject_code', sa.String(length=20), nullable=True, comment='reject status eg RECH_BNUME RECH_PERDI RECH_IDENT RECH_ICCID'),
    sa.Column('description', sa.Text(), nullable=True, comment='Response description from NC'),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='Number of retry attempts'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message'),
    sa.Column('error_description', sa.Text(), nullable=True, comment='Detailed error description'),
    sa.Column('requested_at', sa.TIMESTAMP(), nullable=True, comment='When customer submitted the request'),
    sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=True, comment='When to process next (for retries)'),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True, comment='When request completed successfully'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status_date', sa.TIMESTAMP(), nullable=True, comment='statusDate from NC response - status timestamp'),
    sa.Column('creation_date', sa.TIMESTAMP(), nullable=True, comment='creationDate from NC response - request creation timestamp'),
    sa.Column('subscriber_cancellation_date', sa.TIMESTAMP(), nullable=True, comment='subscriberCancellationDate from NC response'),
    sa.Column('recipient_operator_code', sa.String(length=10), nullable=True, comment='recipientOperatorCode from NC response'),
    sa.Column('donor_operator_code', sa.String(length=10), nullable=True, comment='donorOperatorCode from NC response'),
    sa.Column('change_window_date', sa.TIMESTAMP(), nullable=True, comment='changeWindowDate from NC response - porting date'),
    sa.PrimaryKeyConstraint('id'),
    comment='Mobile number Return requests'
    )
    op.create_index('idx_return_msisdn', 'return_requests', ['msisdn'], unique=False)
    op.create_index('idx_return_reference_code', 'return_requests', ['reference_code'], unique=False)
    op.create_index('idx_return_status_scheduled', 'return_requests', ['status_nc', 'scheduled_at'], unique=False)
    op.create_table('portout_request',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metadata_id', sa.BigInteger(), nullable=False),
    sa.Column('notification_id', sa.String(length=50), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('synchronized', sa.Boolean(), nullable=True),
    sa.Column('reference_code', sa.String(length=50), nullable=True),
    sa.Column('status_bss', sa.String(length=50), nullable=True),
    sa.Column('submitted_to_bss', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='0 - not submitted, 1 - submitted'),
    sa.Column('status_nc', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('response_code', sa.String(length=10), nullable=True),
    sa.Column('confirm_reject', sa.SmallInteger(), nullable=True, comment='confirm=1, reject=2 for offline confirmation to NC'),
    sa.Column('cancellation_reason', sa.String(length=100), nullable=True, comment='eg CANC_ABONA'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='description with return NC on reject or confirm'),
    sa.Column('state_date', sa.DateTime(), nullable=True),
    sa.Column('creation_date_request', sa.DateTime(), nullable=True),
    sa.Column('reading_mark_date', sa.DateTime(), nullable=True),
    sa.Column('state_change_deadline', sa.DateTime(), nullable=True),
    sa.Column('subscriber_request_date', sa.DateTime(), nullable=True),
    sa.Column('donor_operator_code', sa.String(length=10), nullable=True),
    sa.Column('receiver_operator_code', sa.String(length=10), nullable=True),
    sa.Column('extraordinary_donor_activation', sa.Boolean(), nullable=True),
    sa.Column('contract_code', sa.String(length=100), nullable=True),
    sa.Column('receiver_NRN', sa.String(length=50), nullable=True),
    sa.Column('port_window_date', sa.DateTime(), nullable=True),
    sa.Column('port_window_by_subscriber', sa.Boolean(), nullable=True),
    sa.Column('MSISDN', sa.String(length=20), nullable=True),
    sa.Column('subscriber_type', sa.String(length=20), server_default=sa.text("'person'"), nullable=True, comment='person or legal'),
    sa.Column('subscriber_id_type', sa.String(length=10), nullable=True),
    sa.Column('subscriber_id_number', sa.String(length=30), nullable=True),
    sa.Column('subscriber_first_name', sa.String(length=100), nullable=True),
    sa.Column('subscriber_last_name_1', sa.String(length=100), nullable=True),
    sa.Column('subscriber_last_name_2', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('msisdn_single', sa.JSON(), nullable=True, comment='List of individual MSISDNs as strings, e.g., ["621800007"]'),
    sa.Column('msisdn_ranges', sa.JSON(), nullable=True, comment='List of MSISDN range objects, e.g., [{"initial_value": "621800011", "final_value": "621800012"}]'),
    sa.ForeignKeyConstraint(['metadata_id'], ['portout_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metadata_id', 'portout_request', ['metadata_id'], unique=False)
    op.create_index('idx_msisdn', 'portout_request', ['MSISDN'], unique=False)
    op.create_index('idx_reference_code', 'portout_request', ['reference_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reference_code', table_name='portout_request')
    op.drop_index('idx_msisdn', table_name='portout_request')
    op.drop_index('idx_metadata_id', table_name='portout_request')
    op.drop_table('portout_request')
    op.drop_index('idx_return_status_scheduled', table_name='return_requests')
    op.drop_index('idx_return_reference_code', table_name='return_requests')
    op.drop_index('idx_return_msisdn', table_name='return_requests')
    op.drop_table('return_requests')
    op.drop_index('idx_response_code', table_name='portout_metadata')
    op.drop_table('portout_metadata')
    op.drop_index('idx_status_composite', table_name='portability_requests')
    op.drop_index('idx_session_code', table_name='portability_requests')
    op.drop_index('idx_scheduled_status', table_name='portability_requests')
    op.drop_index('idx_reference_code', table_name='portability_requests')
    op.drop_index('idx_msisdn', table_name='portability_requests')
    op.drop_index('idx_donor_recipient', table_name='portability_requests')
    op.drop_index('idx_document', table_name='portability_requests')
    op.drop_index('idx_created_at', table_name='portability_requests')
    op.drop_index('idx_country_type', table_name='portability_requests')
    op.drop_index('idx_completion', table_name='portability_requests')
    op.drop_table('portability_requests')
    op.drop_table('italy_port_in_requests')
    # ### end Alembic commands ###
