"""Corrected length of nationality field from 3 to 64 chars

Revision ID: 1a9e6a2cbd7e
Revises: abc8cbdb6f93
Create Date: 2025-11-19 08:28:56.759906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a9e6a2cbd7e'
down_revision: Union[str, Sequence[str], None] = 'abc8cbdb6f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portability_requests', 'nationality',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("'ESP'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portability_requests', 'nationality',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=True,
               existing_server_default=sa.text("'ESP'"))
    # ### end Alembic commands ###
