"""Exact match portability_requests model_3

Revision ID: 3c4508f3da50
Revises: 4b5dc6945a3f
Create Date: 2025-11-19 08:08:17.322531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c4508f3da50'
down_revision: Union[str, Sequence[str], None] = '4b5dc6945a3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_response_code'), table_name='portout_metadata')
    op.alter_column('portout_request', 'submitted_to_bss',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='0 - not subitted ,1 - submitted',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('portout_request', 'confirm_reject',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.Integer(),
               existing_comment='confirm=1, reject=2 for offline confirmation to NC',
               existing_nullable=True)
    op.alter_column('portout_request', 'description',
               existing_type=mysql.VARCHAR(length=200),
               comment='description with return NC on reject or confirm',
               existing_comment='descroption with return NC on reject or confirm',
               existing_nullable=True)
    op.alter_column('portout_request', 'subscriber_type',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='person or legal',
               existing_nullable=True,
               existing_server_default=sa.text("'person'"))
    op.drop_index(op.f('idx_metadata_id'), table_name='portout_request')
    op.drop_index(op.f('idx_msisdn'), table_name='portout_request')
    op.drop_index(op.f('idx_reference_code'), table_name='portout_request')
    op.drop_constraint(op.f('portout_request_ibfk_1'), 'portout_request', type_='foreignkey')
    op.create_foreign_key(None, 'portout_request', 'portout_metadata', ['metadata_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portout_request', type_='foreignkey')
    op.create_foreign_key(op.f('portout_request_ibfk_1'), 'portout_request', 'portout_metadata', ['metadata_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_reference_code'), 'portout_request', ['reference_code'], unique=False)
    op.create_index(op.f('idx_msisdn'), 'portout_request', ['MSISDN'], unique=False)
    op.create_index(op.f('idx_metadata_id'), 'portout_request', ['metadata_id'], unique=False)
    op.alter_column('portout_request', 'subscriber_type',
               existing_type=mysql.VARCHAR(length=20),
               comment='person or legal',
               existing_nullable=True,
               existing_server_default=sa.text("'person'"))
    op.alter_column('portout_request', 'description',
               existing_type=mysql.VARCHAR(length=200),
               comment='descroption with return NC on reject or confirm',
               existing_comment='description with return NC on reject or confirm',
               existing_nullable=True)
    op.alter_column('portout_request', 'confirm_reject',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=4),
               existing_comment='confirm=1, reject=2 for offline confirmation to NC',
               existing_nullable=True)
    op.alter_column('portout_request', 'submitted_to_bss',
               existing_type=mysql.TINYINT(display_width=1),
               comment='0 - not subitted ,1 - submitted',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_response_code'), 'portout_metadata', ['response_code'], unique=False)
    # ### end Alembic commands ###
