"""add ItalyPortInRequest table

Revision ID: 4ded46e9bac4
Revises: 6d35fb5b683b
Create Date: 2025-12-04 12:33:43.647612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ded46e9bac4'
down_revision: Union[str, Sequence[str], None] = '6d35fb5b683b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('italy_port_in_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_operator', sa.String(length=50), nullable=False),
    sa.Column('file_date', sa.Date(), nullable=False),
    sa.Column('file_time', sa.String(length=8), nullable=False),
    sa.Column('recipient_operator', sa.String(length=50), nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=False),
    sa.Column('message_type_code', sa.String(length=2), nullable=False),
    sa.Column('recipient_operator_code', sa.String(length=50), nullable=False),
    sa.Column('donating_operator_code', sa.String(length=50), nullable=False),
    sa.Column('recipient_request_code', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('iccid_serial_number', sa.String(length=20), nullable=True),
    sa.Column('tax_code_vat', sa.String(length=50), nullable=True),
    sa.Column('payment_type', sa.String(length=3), nullable=True),
    sa.Column('analog_digital_code', sa.String(length=1), nullable=True),
    sa.Column('cut_over_date', sa.Date(), nullable=False),
    sa.Column('customer_first_name', sa.String(length=100), nullable=True),
    sa.Column('customer_last_name', sa.String(length=100), nullable=True),
    sa.Column('imsi', sa.String(length=20), nullable=True),
    sa.Column('credit_transfer_flag', sa.String(length=1), nullable=True),
    sa.Column('routing_number', sa.String(length=10), nullable=True),
    sa.Column('pre_validation_flag', sa.String(length=1), nullable=True),
    sa.Column('theft_flag', sa.String(length=1), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True, comment='When this request is scheduled for processing'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient_request_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('italy_port_in_requests')
    # ### end Alembic commands ###
