"""Update nationality length

Revision ID: 4f54aa23083b
Revises: d0dd6658a207
Create Date: 2025-11-18 21:16:14.874726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4f54aa23083b'
down_revision: Union[str, Sequence[str], None] = 'd0dd6658a207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portability_requests', 'nationality',
               existing_type=mysql.VARCHAR(length=3),
               type_=sa.String(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("'ESP'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portability_requests', 'nationality',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=3),
               existing_nullable=True,
               existing_server_default=sa.text("'ESP'"))
    # ### end Alembic commands ###
