"""Create portout_request table

Revision ID: 64ec26479cf2
Revises: 7c158d738d65
Create Date: 2025-11-18 20:35:18.168116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ec26479cf2'
down_revision: Union[str, Sequence[str], None] = '7c158d738d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portout_request',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metadata_id', sa.BigInteger(), nullable=False),
    sa.Column('notification_id', sa.String(length=50), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('synchronized', sa.Boolean(), nullable=True),
    sa.Column('reference_code', sa.String(length=50), nullable=True),
    sa.Column('status_bss', sa.String(length=50), nullable=True),
    sa.Column('submitted_to_bss', sa.Boolean(), server_default=sa.text('0'), nullable=True),
    sa.Column('status_nc', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('response_code', sa.String(length=10), nullable=True),
    sa.Column('confirm_reject', sa.Integer(), nullable=True, comment='confirm=1, reject=2 for offline confirmation to NC'),
    sa.Column('cancellation_reason', sa.String(length=100), nullable=True, comment='eg CANC_ABONA'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='description with return NC on reject or confirm'),
    sa.Column('state_date', sa.DateTime(), nullable=True),
    sa.Column('creation_date_request', sa.DateTime(), nullable=True),
    sa.Column('reading_mark_date', sa.DateTime(), nullable=True),
    sa.Column('state_change_deadline', sa.DateTime(), nullable=True),
    sa.Column('subscriber_request_date', sa.DateTime(), nullable=True),
    sa.Column('donor_operator_code', sa.String(length=10), nullable=True),
    sa.Column('receiver_operator_code', sa.String(length=10), nullable=True),
    sa.Column('extraordinary_donor_activation', sa.Boolean(), nullable=True),
    sa.Column('contract_code', sa.String(length=100), nullable=True),
    sa.Column('receiver_NRN', sa.String(length=50), nullable=True),
    sa.Column('port_window_date', sa.DateTime(), nullable=True),
    sa.Column('port_window_by_subscriber', sa.Boolean(), nullable=True),
    sa.Column('MSISDN', sa.String(length=20), nullable=True),
    sa.Column('subscriber_type', sa.String(length=20), server_default=sa.text("'person'"), nullable=True),
    sa.Column('subscriber_id_type', sa.String(length=10), nullable=True),
    sa.Column('subscriber_id_number', sa.String(length=30), nullable=True),
    sa.Column('subscriber_first_name', sa.String(length=100), nullable=True),
    sa.Column('subscriber_last_name_1', sa.String(length=100), nullable=True),
    sa.Column('subscriber_last_name_2', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['metadata_id'], ['portout_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portout_request')
    # ### end Alembic commands ###
