"""msisdn can be null - for cancel return

Revision ID: 6b9ae85f260d
Revises: 09c595f557a8
Create Date: 2025-11-21 18:42:36.834162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b9ae85f260d'
down_revision: Union[str, Sequence[str], None] = '09c595f557a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('return_requests', 'msisdn',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True,
               existing_comment='Phone number (9 digits without country code)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('return_requests', 'msisdn',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False,
               existing_comment='Phone number (9 digits without country code)')
    # ### end Alembic commands ###
