"""test run after merge to mani compose.yml

Revision ID: 6d35fb5b683b
Revises: 7c7392b58988
Create Date: 2025-12-04 12:09:25.475517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d35fb5b683b'
down_revision: Union[str, Sequence[str], None] = '7c7392b58988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
