"""Create portout_metadata table

Revision ID: 7c158d738d65
Revises: 
Create Date: 2025-11-18 20:14:23.496689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c158d738d65'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portout_metadata',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('response_code', sa.String(length=50), nullable=True),
    sa.Column('response_description', sa.String(length=255), nullable=True),
    sa.Column('paged_request_code', sa.String(length=100), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('is_last_page', sa.Boolean(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portout_metadata')
    # ### end Alembic commands ###
