"""added msisdn_single, msisdn_range to portout_request

Revision ID: 7c7392b58988
Revises: d5b27b78f3bc
Create Date: 2025-11-27 12:31:06.787736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7392b58988'
down_revision: Union[str, Sequence[str], None] = 'd5b27b78f3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portout_request', sa.Column('msisdn_single', sa.JSON(), nullable=True, comment='List of individual MSISDNs as strings, e.g., ["621800007"]'))
    op.add_column('portout_request', sa.Column('msisdn_ranges', sa.JSON(), nullable=True, comment='List of MSISDN range objects, e.g., [{"initial_value": "621800011", "final_value": "621800012"}]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portout_request', 'msisdn_ranges')
    op.drop_column('portout_request', 'msisdn_single')
    # ### end Alembic commands ###
