"""return request table addition

Revision ID: a2de4da10b74
Revises: 1a9e6a2cbd7e
Create Date: 2025-11-21 13:49:21.302509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2de4da10b74'
down_revision: Union[str, Sequence[str], None] = '1a9e6a2cbd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_type', sa.String(length=20), server_default=sa.text("'RETURN'"), nullable=False, comment='Request type: RETURN'),
    sa.Column('request_date', sa.Date(), nullable=False, comment='Request date from API in YYYY-MM-DD format'),
    sa.Column('msisdn', sa.String(length=15), nullable=False, comment='Phone number (9 digits without country code)'),
    sa.Column('reference_code', sa.String(length=100), nullable=True, comment='CodigoReferencia - Unique reference from NC system'),
    sa.Column('status_bss', sa.String(length=50), server_default=sa.text("'PROCESSING'"), nullable=True, comment='BSS system status: PROCESSING, COMPLETED, FAILED'),
    sa.Column('status_nc', sa.String(length=50), server_default=sa.text("'PENDING'"), nullable=True, comment='NC system status: PENDING, PENDING_RESPONSE, COMPLETED, FAILED'),
    sa.Column('response_code', sa.String(length=20), nullable=True, comment='codigoRespuesta from NC response'),
    sa.Column('response_status', sa.String(length=20), nullable=True, comment='estado - latest response status from NC'),
    sa.Column('reject_code', sa.String(length=20), nullable=True, comment='reject status eg RECH_BNUME RECH_PERDI RECH_IDENT RECH_ICCID'),
    sa.Column('description', sa.Text(), nullable=True, comment='Response description from NC'),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='Number of retry attempts'),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message'),
    sa.Column('error_description', sa.Text(), nullable=True, comment='Detailed error description'),
    sa.Column('requested_at', sa.TIMESTAMP(), nullable=True, comment='When customer submitted the request'),
    sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=True, comment='When to process next (for retries)'),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True, comment='When request completed successfully'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Mobile number Return requests'
    )
    op.create_index('idx_return_msisdn', 'return_requests', ['msisdn'], unique=False)
    op.create_index('idx_return_reference_code', 'return_requests', ['reference_code'], unique=False)
    op.create_index('idx_return_status_scheduled', 'return_requests', ['status_nc', 'scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_return_status_scheduled', table_name='return_requests')
    op.drop_index('idx_return_reference_code', table_name='return_requests')
    op.drop_index('idx_return_msisdn', table_name='return_requests')
    op.drop_table('return_requests')
    # ### end Alembic commands ###
