"""Exact match portability_requests model_4

Revision ID: abc8cbdb6f93
Revises: 3c4508f3da50
Create Date: 2025-11-19 08:14:15.833113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'abc8cbdb6f93'
down_revision: Union[str, Sequence[str], None] = '3c4508f3da50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portout_request', 'submitted_to_bss',
               existing_type=mysql.TINYINT(display_width=1),
               comment='0 - not submitted, 1 - submitted',
               existing_comment='0 - not subitted ,1 - submitted',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('portout_request', 'confirm_reject',
               existing_type=mysql.TINYINT(display_width=4),
               type_=sa.SmallInteger(),
               existing_comment='confirm=1, reject=2 for offline confirmation to NC',
               existing_nullable=True)
    op.alter_column('portout_request', 'description',
               existing_type=mysql.VARCHAR(length=200),
               comment='description with return NC on reject or confirm',
               existing_comment='descroption with return NC on reject or confirm',
               existing_nullable=True)
    op.drop_constraint(op.f('portout_request_ibfk_1'), 'portout_request', type_='foreignkey')
    op.create_foreign_key(None, 'portout_request', 'portout_metadata', ['metadata_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portout_request', type_='foreignkey')
    op.create_foreign_key(op.f('portout_request_ibfk_1'), 'portout_request', 'portout_metadata', ['metadata_id'], ['id'], ondelete='CASCADE')
    op.alter_column('portout_request', 'description',
               existing_type=mysql.VARCHAR(length=200),
               comment='descroption with return NC on reject or confirm',
               existing_comment='description with return NC on reject or confirm',
               existing_nullable=True)
    op.alter_column('portout_request', 'confirm_reject',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=4),
               existing_comment='confirm=1, reject=2 for offline confirmation to NC',
               existing_nullable=True)
    op.alter_column('portout_request', 'submitted_to_bss',
               existing_type=mysql.TINYINT(display_width=1),
               comment='0 - not subitted ,1 - submitted',
               existing_comment='0 - not submitted, 1 - submitted',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
