"""Add portability_requests table

Revision ID: d0dd6658a207
Revises: dbfbd6413e3a
Create Date: 2025-11-18 21:12:13.454236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0dd6658a207'
down_revision: Union[str, Sequence[str], None] = 'dbfbd6413e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portability_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=3), server_default=sa.text("'ESP'"), nullable=False),
    sa.Column('request_type', sa.Enum('PORT_IN', 'PORT_OUT', 'CANCELLATION', 'MULTISIM', 'EXTENSION'), nullable=False),
    sa.Column('cancel_request_id', sa.BigInteger(), server_default=sa.text('0'), nullable=False, comment='id of portin request'),
    sa.Column('reference_code', sa.String(length=100), server_default=sa.text("''"), nullable=True, comment='Unique reference from NC system'),
    sa.Column('session_code', sa.String(length=100), nullable=True, comment='Session identifier from BSS'),
    sa.Column('session_code_nc', sa.String(length=100), nullable=True, comment='Session identifier from NC'),
    sa.Column('request_code', sa.String(length=100), nullable=True, comment='Internal request identifier'),
    sa.Column('status_bss', sa.String(length=100), server_default=sa.text("'PROCESSING'"), nullable=True, comment='BSS system status'),
    sa.Column('status_nc', sa.String(length=50), server_default=sa.text("'PENDING'"), nullable=True, comment='NC system status'),
    sa.Column('response_code', sa.String(length=20), server_default=sa.text("''"), nullable=True, comment='coddigoRespuesta'),
    sa.Column('response_status', sa.String(length=20), server_default=sa.text("''"), nullable=True, comment='Latest response code from NC'),
    sa.Column('reject_code', sa.String(length=10), server_default=sa.text("''"), nullable=True, comment='reject status eg RECH_BNUME RECH_PERDI RECH_IDENT RECH_ICCID'),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True, comment='Last error message'),
    sa.Column('error_description', sa.String(length=255), nullable=True),
    sa.Column('msisdn', sa.String(length=15), server_default=sa.text("''"), nullable=False, comment='Phone number'),
    sa.Column('iccid', sa.String(length=22), nullable=True, comment='SIM card number'),
    sa.Column('subscriber_type', sa.Enum('person', 'company'), nullable=True, comment='person/company'),
    sa.Column('document_type', sa.Enum('NIF', 'CIF', 'NIE', 'PAS'), nullable=False),
    sa.Column('document_number', sa.String(length=50), server_default=sa.text("''"), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('first_surname', sa.String(length=100), nullable=True),
    sa.Column('second_surname', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=3), server_default=sa.text("'ESP'"), nullable=True),
    sa.Column('name_surname', sa.String(length=200), server_default=sa.text("''"), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True, comment='Subscriber contract number'),
    sa.Column('donor_operator', sa.String(length=50), server_default=sa.text("''"), nullable=False, comment='Current operator'),
    sa.Column('recipient_operator', sa.String(length=50), server_default=sa.text("''"), nullable=False, comment='New operator'),
    sa.Column('routing_number', sa.String(length=20), server_default=sa.text("''"), nullable=True, comment='Routing information'),
    sa.Column('desired_porting_date', sa.String(length=20), nullable=True),
    sa.Column('porting_window', sa.DateTime(), nullable=True, comment='Scheduled porting window date/time from NC'),
    sa.Column('reason_code', sa.String(length=50), nullable=True, comment='Reason for port-out'),
    sa.Column('cancellation_reason', sa.String(length=150), nullable=True),
    sa.Column('cancellation_initiated_by_donor', sa.String(length=150), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(), nullable=True, comment='When customer requested'),
    sa.Column('scheduled_at', sa.TIMESTAMP(), nullable=True, comment='When to process next'),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True, comment='When request completed'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('is_legal_entity', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='Flag indicating if this is a legal entity (1) or individual (0)'),
    sa.Column('company_name', sa.String(length=255), nullable=True, comment='Company name for legal entities'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portability_requests')
    # ### end Alembic commands ###
