"""new fields to return_requests as per NC return status response

Revision ID: d5b27b78f3bc
Revises: 6b9ae85f260d
Create Date: 2025-11-25 08:55:11.957109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b27b78f3bc'
down_revision: Union[str, Sequence[str], None] = '6b9ae85f260d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_requests', sa.Column('status_date', sa.TIMESTAMP(), nullable=True, comment='statusDate from NC response - status timestamp'))
    op.add_column('return_requests', sa.Column('creation_date', sa.TIMESTAMP(), nullable=True, comment='creationDate from NC response - request creation timestamp'))
    op.add_column('return_requests', sa.Column('subscriber_cancellation_date', sa.TIMESTAMP(), nullable=True, comment='subscriberCancellationDate from NC response'))
    op.add_column('return_requests', sa.Column('recipient_operator_code', sa.String(length=10), nullable=True, comment='recipientOperatorCode from NC response'))
    op.add_column('return_requests', sa.Column('donor_operator_code', sa.String(length=10), nullable=True, comment='donorOperatorCode from NC response'))
    op.add_column('return_requests', sa.Column('change_window_date', sa.TIMESTAMP(), nullable=True, comment='changeWindowDate from NC response - porting date'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_requests', 'change_window_date')
    op.drop_column('return_requests', 'donor_operator_code')
    op.drop_column('return_requests', 'recipient_operator_code')
    op.drop_column('return_requests', 'subscriber_cancellation_date')
    op.drop_column('return_requests', 'creation_date')
    op.drop_column('return_requests', 'status_date')
    # ### end Alembic commands ###
