# monitoring/compose.yaml
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-mnp
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=7d'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring-network
      - internal-network  # Connect to your main app network
    ports:
      - "127.0.0.1:9095:9090"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  prometheus_data:

networks:
  monitoring-network:
    driver: bridge
  internal-network:
    external: true
    name: mnp-gateway_internal-network  # Use the exact name from docker network ls