# monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mnp-api'
    static_configs:
      - targets: ['mnp-api.olbe.tech']  # Only this one
    metrics_path: /api/v1/metrics
    scheme: https
    scrape_interval: 15s
    scrape_timeout: 10s
    tls_config:
      insecure_skip_verify: true
